spring:
  application:
    name: LibraryManagement

server:
  port: 5000

library:
  initial-books:
    -
      title: "Awlad Haritna"
      author: "Nagib Mahfouz"
    -
      title: "Awlad Haritna"
      author: "Nagib Mahfouz"
    -
      title: "Awlad Haritna"
      author: "Nagib Mahfouz"
    -
      title: "Awlad Haritna"
      author: "Nagib Mahfouz"
    -
      title: "Awlad Haritna"
      author: "Nagib Mahfouz"
    -
      title: "Clean Code"
      author: "Robert Martin"
